### Site metadata ###

site_name: Democraft is at Cubed!
site_description: Informations About DEMOCRAFT for the players, visitors and admins of the Cubed Con
site_url: https://cubed.democraft.fr/

repo_url: https://github.com/democraftmc/cubed-doc
edit_uri: edit/main/docs/docs

### Build settings ###

theme:
  name: material
  language: fr
  logo: img/logo-modified.png
  favicon: img/logo-modified.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/circle-exclamation
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - search.share
    - search.suggest
    - navigation.tabs
    - navigation.instant
    - content.action.edit

  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 🏠 Home: index.md
  # - About MkDocs: about-mkdocs.md
  - 🥐 Français:
      - À Propos: fr/index.md
  - 🍵 English:
      - About: en/index.md
      # - Installation: tutorial/installation.md
      # - Set up project: tutorial/setup-project.md
      # - Advanced: tutorial/advanced.md
      # - Usage: tutorial/usage.md
      # - Deploy: tutorial/deploy.md

extra:
  alternate:
    - name: Français
      link: fr/
      lang: fr
    - name: English
      link: en/
      lang: en
      
  social:
    - icon: fontawesome/solid/globe 
      link: https://democraft.fr
      name: Site Web
    - icon: fontawesome/brands/discord 
      link: https://dsc.gg/democraft
      name: Discord
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/democraftmc
      name: Instagram
    - icon: fontawesome/brands/tiktok 
      link: https://www.tiktok.com/@democraftmc
      name: TikTok
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@democraftmc
      name: Youtube

  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: ‎ 

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      
  - social:
      enabled: true
      cards: true
      cards_dir: img/socials/
      #cards_layout: default/variant
      
  - search:
      lang: 
        - en
        - fr

copyright: Copyright &copy; 2022 - 2023 DEMOCRAFT

      
