### Site metadata ###

site_name: Democraft is at Cubed!
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://cubed.democraft.fr/

repo_url: https://github.com/democraftmc/cubed-doc
edit_uri: edit/master/docs/docs

### Build settings ###

theme:
  name: material
  language: fr
  logo: img/logo.png
  favicon: img/logo.ico
  features:
    - search.share
    - search.suggest

  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Acceuil: fr/index.md
  - Home: en/index.md
  # - About MkDocs: about-mkdocs.md
  # - Tutorial:
      # - TL;DR: tutorial/tldr.md
      # - Installation: tutorial/installation.md
      # - Set up project: tutorial/setup-project.md
      # - Advanced: tutorial/advanced.md
      # - Usage: tutorial/usage.md
      # - Deploy: tutorial/deploy.md

extra:
  alternate:
    - name: Français
      link: fr/
      lang: fr
    - name: English
      link: en/
      lang: en
      
  social:
    - icon: fontawesome/solid/globe 
      link: https://democraft.fr
      name: Site Web
    - icon: fontawesome/brands/discord 
      link: https://dsc.gg/democraft
      name: Discord
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/democraftmc
      name: Instagram
  
  generator: false

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: 

plugins:
  - social:
      enabled: true
      cards: true
      cards_dir: img/socials/
      
  - search:
      lang: 
        - en
        - fr

copyright: Copyright &copy; 2022 - 2023 DEMOCRAFT

      
