### Site metadata ###

site_name: MkDocs Quickstart
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://michaelcurrin.github.io/mkdocs-quickstart/

repo_url: https://github.com/democraftmc/cubed-doc
edit_uri: edit/master/docs/docs

### Build settings ###

theme:
  name: material
  language: fr
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
